################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/apps/Lib/dsplib/src/msp_abs_iq31.c \
../src/apps/Lib/dsplib/src/msp_abs_q15.c \
../src/apps/Lib/dsplib/src/msp_add_iq31.c \
../src/apps/Lib/dsplib/src/msp_add_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_add_iq31.c \
../src/apps/Lib/dsplib/src/msp_cmplx_add_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_bitrev_iq31.c \
../src/apps/Lib/dsplib/src/msp_cmplx_bitrev_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_conj_iq31.c \
../src/apps/Lib/dsplib/src/msp_cmplx_conj_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_fft_auto_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_fft_fixed_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_fft_iq31.c \
../src/apps/Lib/dsplib/src/msp_cmplx_ifft_auto_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_ifft_fixed_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_ifft_iq31.c \
../src/apps/Lib/dsplib/src/msp_cmplx_mac_iq31.c \
../src/apps/Lib/dsplib/src/msp_cmplx_mac_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_mpy_iq31.c \
../src/apps/Lib/dsplib/src/msp_cmplx_mpy_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_mpy_real_iq31.c \
../src/apps/Lib/dsplib/src/msp_cmplx_mpy_real_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_scale_iq31.c \
../src/apps/Lib/dsplib/src/msp_cmplx_scale_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_shift_iq31.c \
../src/apps/Lib/dsplib/src/msp_cmplx_shift_q15.c \
../src/apps/Lib/dsplib/src/msp_cmplx_sub_iq31.c \
../src/apps/Lib/dsplib/src/msp_cmplx_sub_q15.c \
../src/apps/Lib/dsplib/src/msp_fft_auto_q15.c \
../src/apps/Lib/dsplib/src/msp_fft_fixed_q15.c \
../src/apps/Lib/dsplib/src/msp_fft_iq31.c \
../src/apps/Lib/dsplib/src/msp_ifft_auto_q15.c \
../src/apps/Lib/dsplib/src/msp_ifft_fixed_q15.c \
../src/apps/Lib/dsplib/src/msp_ifft_iq31.c \
../src/apps/Lib/dsplib/src/msp_mac_iq31.c \
../src/apps/Lib/dsplib/src/msp_mac_q15.c \
../src/apps/Lib/dsplib/src/msp_max_iq31.c \
../src/apps/Lib/dsplib/src/msp_max_q15.c \
../src/apps/Lib/dsplib/src/msp_max_uq15.c \
../src/apps/Lib/dsplib/src/msp_max_uq31.c \
../src/apps/Lib/dsplib/src/msp_min_iq31.c \
../src/apps/Lib/dsplib/src/msp_min_q15.c \
../src/apps/Lib/dsplib/src/msp_min_uq15.c \
../src/apps/Lib/dsplib/src/msp_min_uq31.c \
../src/apps/Lib/dsplib/src/msp_mpy_iq31.c \
../src/apps/Lib/dsplib/src/msp_mpy_q15.c \
../src/apps/Lib/dsplib/src/msp_neg_iq31.c \
../src/apps/Lib/dsplib/src/msp_neg_q15.c \
../src/apps/Lib/dsplib/src/msp_offset_iq31.c \
../src/apps/Lib/dsplib/src/msp_offset_q15.c \
../src/apps/Lib/dsplib/src/msp_scale_iq31.c \
../src/apps/Lib/dsplib/src/msp_scale_q15.c \
../src/apps/Lib/dsplib/src/msp_shift_iq31.c \
../src/apps/Lib/dsplib/src/msp_shift_q15.c \
../src/apps/Lib/dsplib/src/msp_split_iq31.c \
../src/apps/Lib/dsplib/src/msp_split_q15.c \
../src/apps/Lib/dsplib/src/msp_sub_iq31.c \
../src/apps/Lib/dsplib/src/msp_sub_q15.c \
../src/apps/Lib/dsplib/src/msp_transform_tables.c 

C_DEPS += \
./src/apps/Lib/dsplib/src/msp_abs_iq31.d \
./src/apps/Lib/dsplib/src/msp_abs_q15.d \
./src/apps/Lib/dsplib/src/msp_add_iq31.d \
./src/apps/Lib/dsplib/src/msp_add_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_add_iq31.d \
./src/apps/Lib/dsplib/src/msp_cmplx_add_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_bitrev_iq31.d \
./src/apps/Lib/dsplib/src/msp_cmplx_bitrev_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_conj_iq31.d \
./src/apps/Lib/dsplib/src/msp_cmplx_conj_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_fft_auto_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_fft_fixed_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_fft_iq31.d \
./src/apps/Lib/dsplib/src/msp_cmplx_ifft_auto_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_ifft_fixed_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_ifft_iq31.d \
./src/apps/Lib/dsplib/src/msp_cmplx_mac_iq31.d \
./src/apps/Lib/dsplib/src/msp_cmplx_mac_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_mpy_iq31.d \
./src/apps/Lib/dsplib/src/msp_cmplx_mpy_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_mpy_real_iq31.d \
./src/apps/Lib/dsplib/src/msp_cmplx_mpy_real_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_scale_iq31.d \
./src/apps/Lib/dsplib/src/msp_cmplx_scale_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_shift_iq31.d \
./src/apps/Lib/dsplib/src/msp_cmplx_shift_q15.d \
./src/apps/Lib/dsplib/src/msp_cmplx_sub_iq31.d \
./src/apps/Lib/dsplib/src/msp_cmplx_sub_q15.d \
./src/apps/Lib/dsplib/src/msp_fft_auto_q15.d \
./src/apps/Lib/dsplib/src/msp_fft_fixed_q15.d \
./src/apps/Lib/dsplib/src/msp_fft_iq31.d \
./src/apps/Lib/dsplib/src/msp_ifft_auto_q15.d \
./src/apps/Lib/dsplib/src/msp_ifft_fixed_q15.d \
./src/apps/Lib/dsplib/src/msp_ifft_iq31.d \
./src/apps/Lib/dsplib/src/msp_mac_iq31.d \
./src/apps/Lib/dsplib/src/msp_mac_q15.d \
./src/apps/Lib/dsplib/src/msp_max_iq31.d \
./src/apps/Lib/dsplib/src/msp_max_q15.d \
./src/apps/Lib/dsplib/src/msp_max_uq15.d \
./src/apps/Lib/dsplib/src/msp_max_uq31.d \
./src/apps/Lib/dsplib/src/msp_min_iq31.d \
./src/apps/Lib/dsplib/src/msp_min_q15.d \
./src/apps/Lib/dsplib/src/msp_min_uq15.d \
./src/apps/Lib/dsplib/src/msp_min_uq31.d \
./src/apps/Lib/dsplib/src/msp_mpy_iq31.d \
./src/apps/Lib/dsplib/src/msp_mpy_q15.d \
./src/apps/Lib/dsplib/src/msp_neg_iq31.d \
./src/apps/Lib/dsplib/src/msp_neg_q15.d \
./src/apps/Lib/dsplib/src/msp_offset_iq31.d \
./src/apps/Lib/dsplib/src/msp_offset_q15.d \
./src/apps/Lib/dsplib/src/msp_scale_iq31.d \
./src/apps/Lib/dsplib/src/msp_scale_q15.d \
./src/apps/Lib/dsplib/src/msp_shift_iq31.d \
./src/apps/Lib/dsplib/src/msp_shift_q15.d \
./src/apps/Lib/dsplib/src/msp_split_iq31.d \
./src/apps/Lib/dsplib/src/msp_split_q15.d \
./src/apps/Lib/dsplib/src/msp_sub_iq31.d \
./src/apps/Lib/dsplib/src/msp_sub_q15.d \
./src/apps/Lib/dsplib/src/msp_transform_tables.d 

OBJS += \
./src/apps/Lib/dsplib/src/msp_abs_iq31.obj \
./src/apps/Lib/dsplib/src/msp_abs_q15.obj \
./src/apps/Lib/dsplib/src/msp_add_iq31.obj \
./src/apps/Lib/dsplib/src/msp_add_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_add_iq31.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_add_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_bitrev_iq31.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_bitrev_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_conj_iq31.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_conj_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_fft_auto_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_fft_fixed_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_fft_iq31.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_ifft_auto_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_ifft_fixed_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_ifft_iq31.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_mac_iq31.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_mac_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_mpy_iq31.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_mpy_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_mpy_real_iq31.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_mpy_real_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_scale_iq31.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_scale_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_shift_iq31.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_shift_q15.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_sub_iq31.obj \
./src/apps/Lib/dsplib/src/msp_cmplx_sub_q15.obj \
./src/apps/Lib/dsplib/src/msp_fft_auto_q15.obj \
./src/apps/Lib/dsplib/src/msp_fft_fixed_q15.obj \
./src/apps/Lib/dsplib/src/msp_fft_iq31.obj \
./src/apps/Lib/dsplib/src/msp_ifft_auto_q15.obj \
./src/apps/Lib/dsplib/src/msp_ifft_fixed_q15.obj \
./src/apps/Lib/dsplib/src/msp_ifft_iq31.obj \
./src/apps/Lib/dsplib/src/msp_mac_iq31.obj \
./src/apps/Lib/dsplib/src/msp_mac_q15.obj \
./src/apps/Lib/dsplib/src/msp_max_iq31.obj \
./src/apps/Lib/dsplib/src/msp_max_q15.obj \
./src/apps/Lib/dsplib/src/msp_max_uq15.obj \
./src/apps/Lib/dsplib/src/msp_max_uq31.obj \
./src/apps/Lib/dsplib/src/msp_min_iq31.obj \
./src/apps/Lib/dsplib/src/msp_min_q15.obj \
./src/apps/Lib/dsplib/src/msp_min_uq15.obj \
./src/apps/Lib/dsplib/src/msp_min_uq31.obj \
./src/apps/Lib/dsplib/src/msp_mpy_iq31.obj \
./src/apps/Lib/dsplib/src/msp_mpy_q15.obj \
./src/apps/Lib/dsplib/src/msp_neg_iq31.obj \
./src/apps/Lib/dsplib/src/msp_neg_q15.obj \
./src/apps/Lib/dsplib/src/msp_offset_iq31.obj \
./src/apps/Lib/dsplib/src/msp_offset_q15.obj \
./src/apps/Lib/dsplib/src/msp_scale_iq31.obj \
./src/apps/Lib/dsplib/src/msp_scale_q15.obj \
./src/apps/Lib/dsplib/src/msp_shift_iq31.obj \
./src/apps/Lib/dsplib/src/msp_shift_q15.obj \
./src/apps/Lib/dsplib/src/msp_split_iq31.obj \
./src/apps/Lib/dsplib/src/msp_split_q15.obj \
./src/apps/Lib/dsplib/src/msp_sub_iq31.obj \
./src/apps/Lib/dsplib/src/msp_sub_q15.obj \
./src/apps/Lib/dsplib/src/msp_transform_tables.obj 

OBJS__QUOTED += \
"src/apps/Lib/dsplib/src/msp_abs_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_abs_q15.obj" \
"src/apps/Lib/dsplib/src/msp_add_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_add_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_add_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_add_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_bitrev_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_bitrev_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_conj_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_conj_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_fft_auto_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_fft_fixed_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_fft_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_ifft_auto_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_ifft_fixed_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_ifft_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_mac_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_mac_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_mpy_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_mpy_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_mpy_real_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_mpy_real_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_scale_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_scale_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_shift_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_shift_q15.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_sub_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_cmplx_sub_q15.obj" \
"src/apps/Lib/dsplib/src/msp_fft_auto_q15.obj" \
"src/apps/Lib/dsplib/src/msp_fft_fixed_q15.obj" \
"src/apps/Lib/dsplib/src/msp_fft_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_ifft_auto_q15.obj" \
"src/apps/Lib/dsplib/src/msp_ifft_fixed_q15.obj" \
"src/apps/Lib/dsplib/src/msp_ifft_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_mac_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_mac_q15.obj" \
"src/apps/Lib/dsplib/src/msp_max_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_max_q15.obj" \
"src/apps/Lib/dsplib/src/msp_max_uq15.obj" \
"src/apps/Lib/dsplib/src/msp_max_uq31.obj" \
"src/apps/Lib/dsplib/src/msp_min_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_min_q15.obj" \
"src/apps/Lib/dsplib/src/msp_min_uq15.obj" \
"src/apps/Lib/dsplib/src/msp_min_uq31.obj" \
"src/apps/Lib/dsplib/src/msp_mpy_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_mpy_q15.obj" \
"src/apps/Lib/dsplib/src/msp_neg_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_neg_q15.obj" \
"src/apps/Lib/dsplib/src/msp_offset_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_offset_q15.obj" \
"src/apps/Lib/dsplib/src/msp_scale_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_scale_q15.obj" \
"src/apps/Lib/dsplib/src/msp_shift_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_shift_q15.obj" \
"src/apps/Lib/dsplib/src/msp_split_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_split_q15.obj" \
"src/apps/Lib/dsplib/src/msp_sub_iq31.obj" \
"src/apps/Lib/dsplib/src/msp_sub_q15.obj" \
"src/apps/Lib/dsplib/src/msp_transform_tables.obj" 

C_DEPS__QUOTED += \
"src/apps/Lib/dsplib/src/msp_abs_iq31.d" \
"src/apps/Lib/dsplib/src/msp_abs_q15.d" \
"src/apps/Lib/dsplib/src/msp_add_iq31.d" \
"src/apps/Lib/dsplib/src/msp_add_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_add_iq31.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_add_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_bitrev_iq31.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_bitrev_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_conj_iq31.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_conj_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_fft_auto_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_fft_fixed_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_fft_iq31.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_ifft_auto_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_ifft_fixed_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_ifft_iq31.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_mac_iq31.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_mac_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_mpy_iq31.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_mpy_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_mpy_real_iq31.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_mpy_real_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_scale_iq31.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_scale_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_shift_iq31.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_shift_q15.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_sub_iq31.d" \
"src/apps/Lib/dsplib/src/msp_cmplx_sub_q15.d" \
"src/apps/Lib/dsplib/src/msp_fft_auto_q15.d" \
"src/apps/Lib/dsplib/src/msp_fft_fixed_q15.d" \
"src/apps/Lib/dsplib/src/msp_fft_iq31.d" \
"src/apps/Lib/dsplib/src/msp_ifft_auto_q15.d" \
"src/apps/Lib/dsplib/src/msp_ifft_fixed_q15.d" \
"src/apps/Lib/dsplib/src/msp_ifft_iq31.d" \
"src/apps/Lib/dsplib/src/msp_mac_iq31.d" \
"src/apps/Lib/dsplib/src/msp_mac_q15.d" \
"src/apps/Lib/dsplib/src/msp_max_iq31.d" \
"src/apps/Lib/dsplib/src/msp_max_q15.d" \
"src/apps/Lib/dsplib/src/msp_max_uq15.d" \
"src/apps/Lib/dsplib/src/msp_max_uq31.d" \
"src/apps/Lib/dsplib/src/msp_min_iq31.d" \
"src/apps/Lib/dsplib/src/msp_min_q15.d" \
"src/apps/Lib/dsplib/src/msp_min_uq15.d" \
"src/apps/Lib/dsplib/src/msp_min_uq31.d" \
"src/apps/Lib/dsplib/src/msp_mpy_iq31.d" \
"src/apps/Lib/dsplib/src/msp_mpy_q15.d" \
"src/apps/Lib/dsplib/src/msp_neg_iq31.d" \
"src/apps/Lib/dsplib/src/msp_neg_q15.d" \
"src/apps/Lib/dsplib/src/msp_offset_iq31.d" \
"src/apps/Lib/dsplib/src/msp_offset_q15.d" \
"src/apps/Lib/dsplib/src/msp_scale_iq31.d" \
"src/apps/Lib/dsplib/src/msp_scale_q15.d" \
"src/apps/Lib/dsplib/src/msp_shift_iq31.d" \
"src/apps/Lib/dsplib/src/msp_shift_q15.d" \
"src/apps/Lib/dsplib/src/msp_split_iq31.d" \
"src/apps/Lib/dsplib/src/msp_split_q15.d" \
"src/apps/Lib/dsplib/src/msp_sub_iq31.d" \
"src/apps/Lib/dsplib/src/msp_sub_q15.d" \
"src/apps/Lib/dsplib/src/msp_transform_tables.d" 

C_SRCS__QUOTED += \
"../src/apps/Lib/dsplib/src/msp_abs_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_abs_q15.c" \
"../src/apps/Lib/dsplib/src/msp_add_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_add_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_add_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_add_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_bitrev_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_bitrev_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_conj_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_conj_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_fft_auto_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_fft_fixed_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_fft_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_ifft_auto_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_ifft_fixed_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_ifft_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_mac_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_mac_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_mpy_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_mpy_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_mpy_real_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_mpy_real_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_scale_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_scale_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_shift_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_shift_q15.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_sub_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_cmplx_sub_q15.c" \
"../src/apps/Lib/dsplib/src/msp_fft_auto_q15.c" \
"../src/apps/Lib/dsplib/src/msp_fft_fixed_q15.c" \
"../src/apps/Lib/dsplib/src/msp_fft_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_ifft_auto_q15.c" \
"../src/apps/Lib/dsplib/src/msp_ifft_fixed_q15.c" \
"../src/apps/Lib/dsplib/src/msp_ifft_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_mac_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_mac_q15.c" \
"../src/apps/Lib/dsplib/src/msp_max_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_max_q15.c" \
"../src/apps/Lib/dsplib/src/msp_max_uq15.c" \
"../src/apps/Lib/dsplib/src/msp_max_uq31.c" \
"../src/apps/Lib/dsplib/src/msp_min_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_min_q15.c" \
"../src/apps/Lib/dsplib/src/msp_min_uq15.c" \
"../src/apps/Lib/dsplib/src/msp_min_uq31.c" \
"../src/apps/Lib/dsplib/src/msp_mpy_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_mpy_q15.c" \
"../src/apps/Lib/dsplib/src/msp_neg_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_neg_q15.c" \
"../src/apps/Lib/dsplib/src/msp_offset_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_offset_q15.c" \
"../src/apps/Lib/dsplib/src/msp_scale_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_scale_q15.c" \
"../src/apps/Lib/dsplib/src/msp_shift_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_shift_q15.c" \
"../src/apps/Lib/dsplib/src/msp_split_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_split_q15.c" \
"../src/apps/Lib/dsplib/src/msp_sub_iq31.c" \
"../src/apps/Lib/dsplib/src/msp_sub_q15.c" \
"../src/apps/Lib/dsplib/src/msp_transform_tables.c" 


